    server:
      allowed_domains:
        - '{{APP_TLD}}'
        - 'localhost'
      name: jitsu
      auth: '${env.CONFIGURATOR_ADMIN_TOKEN}'

    storage:
      redis:
        host: '${env.REDIS_URL}'
        port: 6379
        tls_skip_verify: '${env.TLS_SKIP_VERIFY|false}'

    jitsu:
      base_url: 'http://localhost:8001'
      admin_token: '${env.SERVER_ADMIN_TOKEN}'

    auth:
      redis:
        host: '${env.REDIS_URL}'
        port: 6379
        tls_skip_verify: '${env.TLS_SKIP_VERIFY|false}'
        access_secret: '${env.UI_AUTH_ACCESS_SECRET}'
        refresh_secret: '${env.UI_AUTH_REFRESH_SECRET}'